### ISSUE TITLE
ABout arduino

### ISSUE THREAD

**Issue by chronicle972** [bipropellant/bipropellant-hoverboard-api#4]
i can figure out how Im suppose t use the arduino with , There is some Howto somewhere ?

**Comment by p-h-a-i-l** [comment]
Sorry, no howto yet. Maybe I can walk you through it by answering your questions, and you could document your experience by putting it into a howto for others?

First, you'll need to bipropellant-hoverboard-firmware running on your board in a UART config.

**Comment by chronicle972** [comment]
OK , im not that good at all of this , so I hope my questions wont be too stupid. 
1- I'm guessinng I need to compile it in a hex file then  put it on the board with the st link ? 
2- what do you mean by UART config ?

**Comment by p-h-a-i-l** [comment]
Yes, you need to compile and flash the board.
The firmware can work with many different input methods, you need to specify it through precompiler switches. Usually in config.h.

**Comment by verial** [comment]
I also did not work, what parameters to choose the gpio ?

**Comment by verial** [comment]
I also did not work, what parameters to choose the gpio ?

**Comment by p-h-a-i-l** [comment]
Could you elaborate a little what you tried and how it failed? What gpio?

**Comment by verial** [comment]
I compiled your program as is and flashed the gyro controller go data only on PA2.

**Comment by chronicle972** [comment]
I have this error when i try to put the api on the arduino :
fatal error: hbprotocol/protocol.h: No such file or directory

**Comment by p-h-a-i-l** [comment]
Sorry, I'm not able to follow what you are doing. Which gyro controller? What about PA2?
