### ISSUE TITLE
can't connect to hoverboard using Esp8266 and Arduino

### ISSUE THREAD

**Issue by rizals** [bipropellant/bipropellant-hoverboard-api#7]
Please your help my Esp8266 board can't connect to HB (not spin wheels) and read sensor data use sample script bipropellant-hoverboard-api, Im using online firmware (https://pionierland.de/hoverhack/ : bipropellant/bipropellant-hoverboard-firmware) not setting using default configuration.

**Comment by p-h-a-i-l** [comment]
Hello @rizals you need to configure which USART you want to use in config.h. Default is hoverboard mode.
